Repository streamnative/pulsarctl, pull requests merged in 2019-11, with the labels that each got.

#130 [Issue:128] Fix deploying python function
  pkg/ctl/functions/querystate.go
  pkg/ctl/functions/util.go
  pkg/pulsar/utils/function_confg.go
  pkg/pulsar/utils/window_confing.go
Labels: area/pulsar/functions, type/bug

#132 [BK-SUPPORT-PART-1] Separate HTTP client and admin client
  examples.go
  pkg/auth/auth_provider.go
  pkg/auth/tls.go
  pkg/auth/token.go
  pkg/cli/client.go
  pkg/cli/errors.go
  pkg/cmdutils/config.go
  pkg/ctl/sources/get_test.go
  pkg/pulsar/admin.go
  pkg/pulsar/admin_config.go
  pkg/pulsar/broker_stats.go
  pkg/pulsar/brokers.go
  pkg/pulsar/cluster.go
  pkg/pulsar/functions.go
  pkg/pulsar/functions_worker.go
  pkg/pulsar/namespace.go
  pkg/pulsar/ns_isolation_policy.go
  pkg/pulsar/resource_quotas.go
  pkg/pulsar/schema.go
  pkg/pulsar/sinks.go
  pkg/pulsar/sources.go
  pkg/pulsar/subscription.go
  pkg/pulsar/tenant.go
  pkg/pulsar/topic.go
Labels: area/bookies

#134 [BK-SUPPORT-PART-2] Support bookkeeper ledger commands
  pkg/bkctl/bk.go
  pkg/bkctl/ledger/delete.go
  pkg/bkctl/ledger/delete_test.go
  pkg/bkctl/ledger/errors.go
  pkg/bkctl/ledger/get.go
  pkg/bkctl/ledger/get_test.go
  pkg/bkctl/ledger/ledger.go
  pkg/bkctl/ledger/list.go
  pkg/bkctl/ledger/read.go
  pkg/bkctl/ledger/read_test.go
  pkg/bkctl/ledger/test_help.go
  pkg/bookkeeper/admin.go
  pkg/bookkeeper/admin_config.go
  pkg/bookkeeper/bkdata/api_version.go
  pkg/bookkeeper/bkdata/ledger_metadata.go
  pkg/bookkeeper/ledger.go
  pkg/cmdutils/cmdutils.go
  pkg/cmdutils/config.go
  pkg/pulsarctl.go
Labels: area/bookies

#143 Fix int overflows
  pkg/ctl/namespace/create.go
Labels: type/bug

#144 Remove the BookKeeper commands
  pkg/pulsarctl.go
Labels: area/bookies, type/task

#146 Add new available release to the README
  README.md
Labels: area/documentation
