Repository streamnative/pulsarctl, pull requests merged in 2019-10, with the labels that each got.

#113 Remove `sudo` from the build script
  Makefile
Labels: area/ci

#115 Fix build doc error
  Makefile
Labels: area/ci

#117 Release uploads the site package
  .github/workflows/release.yml
  .gitignore
  Makefile
Labels: area/ci, type/task

#121 Add a table of releases
  README.md
Labels: area/documentation

#123 Support publish the windows binary package and drawin binary package
  .github/workflows/release.yml
  README.md
  install.sh
  stable.txt
Labels: area/ci
