Repository streamnative/pulsarctl, pull requests merged in 2020-07, with the labels that each got.

#233 Support oauth2 authentication for pulsarctl
  go.mod
  go.sum
  pkg/auth/auth_provider.go
  pkg/auth/oauth2.go
  pkg/auth/oauth2/auth.go
  pkg/auth/oauth2/auth_suite_test.go
  pkg/auth/oauth2/authorization_tokenretriever.go
  pkg/auth/oauth2/authorization_tokenretriever_test.go
  pkg/auth/oauth2/client_credentials_flow.go
  pkg/auth/oauth2/client_credentials_flow_test.go
  pkg/auth/oauth2/client_credentials_provider.go
  pkg/auth/oauth2/config_tokenprovider.go
  pkg/auth/oauth2/config_tokenprovider_test.go
  pkg/auth/oauth2/oidc_endpoint_provider.go
  pkg/auth/oauth2/oidc_endpoint_provider_test.go
  pkg/auth/oauth2/plugin/clock.go
  pkg/auth/oauth2/plugin/fake_clock.go
  pkg/auth/oauth2_test.go
  pkg/cmdutils/config.go
  pkg/cmdutils/ctx_conf.go
  pkg/ctl/context/create_context.go
  pkg/ctl/context/create_context_test.go
  pkg/ctl/context/test_help.go
  pkg/pulsar/common/config.go
Labels: P1, product/cloud, triage/week-26, workflow::in-review

#229 Fix wrong context panic
  pkg/cmdutils/config.go
Labels: triage/week-26, type/bug, workflow::in-review

#234 Fix the failed tests
  pkg/ctl/context/current_context_test.go
  pkg/ctl/namespace/delete_test.go
  pkg/ctl/namespace/grant_permission_test.go
  pkg/ctl/namespace/grant_subscription_permission_test.go
  pkg/ctl/namespace/policies_test.go
  pkg/ctl/namespace/topics_test.go
Labels: workflow::in-review
