Repository streamnative/pulsarctl, pull requests merged in 2020-01, with the labels that each got.

#165 Fix parse wrong http header when receive pulsar header
  pkg/pulsar/subscription.go
Labels: area/pulsar/subscriptions, type/bug

#172 [issue-171] Improve tab alignment of help text
  pkg/cmdutils/group.go
  pkg/ctl/functions/create.go
  pkg/ctl/tenant/delete.go
Labels: type/enhancement

#167 Using testcontainer to create a test framework for testing
  go.mod
  go.sum
  pkg/test/base_container.go
  pkg/test/pulsar/cluster.go
  pkg/test/pulsar/cluster_script.go
  pkg/test/pulsar/cluster_spec.go
  pkg/test/pulsar/cluster_test.go
  pkg/test/pulsar/containers/bookie.go
  pkg/test/pulsar/containers/broker.go
  pkg/test/pulsar/containers/proxy.go
  pkg/test/pulsar/containers/zookeeper.go
  pkg/test/pulsar/standalone.go
  pkg/test/pulsar/standalone_test.go
  pkg/test/utils.go
Labels: type/enhancement, type/task, workflow::in-review

#175 Add bookkeeper related commands to auto generated docs
  pkg/pulsarctl.go
  site/gen-pulsarctldocs/generators/v1_1/toc.yaml
Labels: area/bookies

#170 Add test for the auto recovery command
  go.mod
  go.sum
  pkg/bkctl/autorecovery/decommission.go
  pkg/bkctl/autorecovery/lost_bookie_recovery_delay_test.go
  pkg/bkctl/autorecovery/test_help.go
  pkg/bkctl/autorecovery/trigger_audit_test.go
  pkg/bkctl/autorecovery/who_is_auditor.go
  pkg/bkctl/autorecovery/who_is_auditor_test.go
  pkg/bookkeeper/autorecovery.go
  pkg/test/bookkeeper/bkctl.go
  pkg/test/bookkeeper/cluster.go
  pkg/test/bookkeeper/cluster_spec.go
  pkg/test/utils.go
Labels: workflow::in-review

#174 [doc] update README to install pulsarctl using brew tap
  README.md
Labels: area/documentation

#177 ignore docs in action CI
  .github/workflows/bookkeeper.yml
  .github/workflows/go.yml
  .github/workflows/project.yml
  .github/workflows/release-check.yml
  .github/workflows/release-note.yml
  .github/workflows/tls.yml
  .github/workflows/token.yml
Labels: area/ci

#169 Add context for pulsarctl
  docs/en/enable_completion.md
  docs/en/how-to-use-context.md
  docs/en/overview_of_pulsarctl.md
  go.mod
  go.sum
  golangci.yml
  pkg/cmdutils/config.go
  pkg/cmdutils/ctx_conf.go
  pkg/ctl/cluster/test.go
  pkg/ctl/context/context.go
  pkg/ctl/context/create_context.go
  pkg/ctl/context/create_context_test.go
  pkg/ctl/context/current_context.go
  pkg/ctl/context/current_context_test.go
  pkg/ctl/context/delete_context.go
  pkg/ctl/context/delete_context_test.go
  pkg/ctl/context/get_contexts.go
  pkg/ctl/context/internal/client_config.go
  pkg/ctl/context/internal/config_access.go
  pkg/ctl/context/internal/loader.go
  pkg/ctl/context/rename_context.go
  pkg/ctl/context/rename_context_test.go
  pkg/ctl/context/test_help.go
  pkg/ctl/context/use_context.go
  pkg/pulsar/utils/home_dir.go
  pkg/pulsarctl.go
  site/gen-pulsarctldocs/generators/v1_1/toc.yaml
Labels: type/feature

#181 [issue-126] Implement JSON output format for list commands
  go.mod
  go.sum
  pkg/bookkeeper/admin.go
  pkg/cmdutils/output.go
  pkg/cmdutils/output_test.go
  pkg/cmdutils/verb.go
  pkg/ctl/brokers/list.go
  pkg/ctl/brokers/list_dynamic_config.go
  pkg/ctl/cluster/get_peer_clusters.go
  pkg/ctl/cluster/list.go
  pkg/ctl/functions/list.go
  pkg/ctl/namespace/list.go
  pkg/ctl/namespace/topics.go
  pkg/ctl/sinks/list.go
  pkg/ctl/sources/list.go
  pkg/ctl/subscription/list.go
  pkg/ctl/tenant/list.go
  pkg/ctl/topic/list.go
Labels: workflow::in-review

#186 [issue-126] Output formats for 'get' commands
  pkg/cmdutils/output.go
  pkg/cmdutils/output_test.go
  pkg/ctl/brokers/config.go
  pkg/ctl/brokers/get_all_dynamic_config.go
  pkg/ctl/brokers/get_runtime_config.go
  pkg/ctl/brokers/namespaces.go
  pkg/ctl/cluster/get.go
  pkg/ctl/cluster/get_failure_domain.go
  pkg/ctl/cluster/list_failure_domain.go
  pkg/ctl/functions/get.go
  pkg/ctl/functions/querystate.go
  pkg/ctl/functions/stats.go
  pkg/ctl/functions/status.go
  pkg/ctl/functionsworker/function_stats.go
  pkg/ctl/functionsworker/get_cluster.go
  pkg/ctl/functionsworker/get_cluster_leader.go
  pkg/ctl/functionsworker/get_function_assignments.go
  pkg/ctl/functionsworker/monitoring_metrics.go
  pkg/ctl/namespace/permissions.go
  pkg/ctl/namespace/policies.go
  pkg/ctl/nsisolationpolicy/broker.go
  pkg/ctl/nsisolationpolicy/brokers.go
  pkg/ctl/nsisolationpolicy/get.go
  pkg/ctl/nsisolationpolicy/list.go
  pkg/ctl/resourcequotas/get.go
  pkg/ctl/schemas/get.go
  pkg/ctl/sinks/get.go
  pkg/ctl/sinks/status.go
  pkg/ctl/sources/get.go
  pkg/ctl/sources/status.go
  pkg/ctl/tenant/get.go
  pkg/ctl/topic/bundle_range.go
  pkg/ctl/topic/compact_status.go
  pkg/ctl/topic/get.go
  pkg/ctl/topic/get_permissions.go
  pkg/ctl/topic/internal.go
  pkg/ctl/topic/last_messageId.go
  pkg/ctl/topic/lookup_topic.go
  pkg/ctl/topic/offload_status.go
  pkg/ctl/topic/stats.go
  pkg/ctl/topic/stats_internal.go
Labels: type/enhancement, type/task

#187 Update the VERSION file and stable.txt
  VERSION
  stable.txt
Labels: workflow::in-review

#192 Fix maven broken link
  .github/workflows/go.yml
  pkg/ctl/brokers/config_test.go
  pkg/ctl/brokers/list_dynamic_config_test.go
  pkg/ctl/sinks/status_test.go
Labels: workflow::in-review

#195 [issue-126] Add information about output formats to developer guide
  docs/en/developer-guide.md
Labels: documentation

#193 Automatically use a context when it is added
  pkg/ctl/context/create_context.go
  pkg/ctl/context/create_context_test.go
  pkg/ctl/context/delete_context_test.go
  pkg/ctl/context/rename_context_test.go
Labels: type/enhancement

#196 Rework auth and add pulsar client conf
  examples.go
  go.mod
  go.sum
  pkg/auth/auth_provider.go
  pkg/auth/tls.go
  pkg/auth/token.go
  pkg/auth/token_test.go
  pkg/cli/client.go
  pkg/cmdutils/config.go
  pkg/pulsar/admin.go
  pkg/pulsar/common/config.go
  pkg/pulsar/defaults.go
Labels: type/feature

#199 [issue:182] get-function-assignments has incorrect output
  pkg/ctl/functionsworker/get_function_assignments.go
  pkg/pulsar/admin.go
Labels: area/pulsar/functions, type/bug

#202 Change NameSpaceAuth to be an [] of AuthAction
  pkg/pulsar/common/auth_polices.go
Labels: type/bug

#200 Add update homebrew formula in the release process
  docs/en/release_process.md
Labels: documentation

#188 Using plugin handler to add other pulsar related tools
  docs/en/how-to-extend-pulsarctl-with-plugins.md
  main.go
  pkg/plugin/plugin.go
  pkg/pulsarctl.go
Labels: area/framework, type/feature, workflow::in-review
