Repository streamnative/pulsarctl, pull requests merged in 2022-10, with the labels that each got.

#853 Update pulsar client go version for pulsarctl
  go.mod
  go.sum
Labels: doc-info-missing

#858 add fields to topic stats
  pkg/pulsar/utils/data.go
Labels: doc-required

#860 add estimated backlog size to topic stats
  pkg/pulsar/utils/data.go
Labels: doc-required

#857 fix: upgrade the alpine to fix CVE-2022-37434
  docker/amd64-linux.Dockerfile
Labels: no-need-doc
