Repository streamnative/pulsarctl, pull requests merged in 2023-05, with the labels that each got.

#1034 fix policies typo
  pkg/ctl/namespace/create.go
  pkg/ctl/namespace/policies_test.go
Labels: no-need-doc

#1066 Revert "fix policies typo (#1034)"
  pkg/ctl/namespace/create.go
  pkg/ctl/namespace/policies_test.go
Labels: doc-info-missing

#1067 fix: Fix TestUpdateTopicNotExist and TestUpdateNonPartitionedTopic
  pkg/ctl/topic/update_test.go
Labels: no-need-doc

#1065 Bump pulsar version to 3.0.0.1
  .github/workflows/ci-functions-checks.yml
  .github/workflows/ci-packages-checks.yml
  pkg/ctl/namespace/clusters_test.go
  pkg/ctl/namespace/create_test.go
  pkg/ctl/namespace/replicator_dispatch_rate_test.go
  pkg/ctl/topic/update_test.go
  scripts/run-integration-tests.sh
  scripts/test-docker/Dockerfile
Labels: no-need-doc

#1072 Removed error char for auto generate docs site
  pkg/cmdutils/config.go
Labels: doc-info-missing

#1084 Fixed remove auth plugin suffix
  pkg/cmdutils/config.go
Labels: no-need-doc

#1081 feat: auto activate oauth2 client credentials
  pkg/cmdutils/config.go
  pkg/oauth2/active.go
Labels: doc-required
